name: Check code

on: [pull_request]

jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install deps
        run: pip install flake8 black isort
      - name: Run linter
        run: flake8 ./
      - name: Run formatting
        run: black --check ./ && isort --check ./